''' Subjects.py

This module contains the list of subjects used to generate prompts.
'''
subjects = [
    "Create 4 prompts about: Steampunk romance novels",
    "Create 3 prompts about: Cyberpunk thrillers set in virtual reality worlds",
    "Create 5 prompts about: Time-traveling adventures through different eras of history",
    "Create 2 prompts about: Existential crises faced by AI personalities",
    "Create 1 prompt about: Alien encounters with human psychologists",
    "Create 4 prompts about: Gritty, hard-boiled detective novels set in a dystopian metropolis",
    "Create 3 prompts about: Psychological thrillers centered around mind-reading abilities",
    "Create 2 prompts about: Intergalactic wars between rival alien empires",
    "Create 5 prompts about: Immersive VR experiences simulating different cultures and societies",
    "Create 4 prompts about: Fantastical creatures living in harmony with nature",
    "Create 3 prompts about: Ancient civilizations rediscovering lost technologies",
    "Create 2 prompts about: Artificial intelligence surpassing human capabilities",
    "Create 1 prompt about: Virtual reality worlds reflecting the subconscious minds of their users",
    "Create 4 prompts about: Time-traveling heroes changing the course of history",
    "Create 3 prompts about: Alternate realities and parallel universes",
    "Create 2 prompts about: Superpowered beings struggling with personal demons",
    "Create 3 prompts about: A mermaid riding a unicorn",
    "Create 4 prompts about: A city in the clouds",
    "Create 5 prompts about: A giant pineapple on a tropical island",
    "Create 2 prompts about: A little robot with a big smile",
    "Create 1 prompt about: A dragon playing the piano",
    "Create 4 prompts about: A vintage car driving through a field of sunflowers",
    "Create 3 prompts about: A group of jellyfish having a dance party",
    "Create 2 prompts about: A castle made entirely of candy",
    "Create 5 prompts about: A superhero squirrel saving the day",
    "Create 4 prompts about: A treehouse hidden in a giant oak tree",
    "Create 3 prompts about: A parade of penguins marching through Antarctica",
    "Create 2 prompts about: A hot air balloon flying over a rainbow-colored city",
    "Create 1 prompt about: A talking eggplant giving a lecture on philosophy",
    "Create 4 prompts about: A school of fish doing synchronized swimming",
    "Create 3 prompts about: A giant mushroom growing in a fairy forest",
    "Create 5 prompts about: A little cat with a big hat",
    "Create 2 prompts about: A robot playing the harmonica on a moonlit beach",
    "Create 4 prompts about: A group of fairies having a tea party in a magical meadow",
    "Create 3 prompts about: A train made entirely of candy chugging through a sugary landscape",
    "Create 2 prompts about: A group of mermaids singing in harmony underwater"
]